apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: davinci
  labels:
    strimzi.io/cluster: my-devcluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: mytopic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: mytopic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: artist
          patternType: literal
        operation: Read
