apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: mytopic
  labels:
    strimzi.io/cluster: my-devcluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

