apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-mgb
spec:
  kafka:
    version: 2.7.0 
    replicas: 1 
    resources: 
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
      jvmOptions: 
        -Xms: 1024m
        -Xmx: 1024m
    listeners: 
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config: 
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage: 
      type: persistent-claim
      size: 100Gi
      class: standard
      deleteClaim: false
    logging: 
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
  zookeeper: 
    replicas: 1
    storage:
      type: persistent-claim
      size: 50Gi
      class: standard
      deleteClaim: false
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1.5"
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
  entityOperator: #11
    topicOperator: {}
    userOperator: {}