apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: rest-proxy
    spec:
      containers:
        - env:
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: xxx.us-east-2.aws.confluent.cloud:9092
            - name: KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE
              value: USER_INFO
            - name: KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS
              value: xxx.us-east-2.aws.confluent.cloud:9092
            - name: KAFKA_REST_CLIENT_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxx' password='xxx';
            - name: KAFKA_REST_CLIENT_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_REST_CLIENT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
              value: KHFKTIX4WEBNDUTY:Crv3CSy5wRikD5MJRbR9neMlCwehNL2dYDc1rH9SQSt5yfb8ifzW9HYTKEhbWb6l
            - name: KAFKA_REST_CLIENT_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_REST_HOST_NAME
              value: rest-proxy
            - name: KAFKA_REST_JMX_OPTS
              value: -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1095 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=1095
            - name: KAFKA_REST_JMX_PORT
              value: "1095"
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxx' password='xxx';
            - name: KAFKA_REST_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: https://xxx.us-east-2.aws.confluent.cloud
            - name: KAFKA_REST_SECURITY_PROTOCOL
              value: SASL_SSL
          image: confluentinc/cp-kafka-rest:7.0.1
          name: rest-proxy
          ports:
            - containerPort: 8082
            - containerPort: 1095
          resources: {}
      hostname: rest-proxy
      restartPolicy: Always
status: {}
