apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
    - name: "1095"
      port: 1095
      targetPort: 1095
  selector:
    io.kompose.service: rest-proxy
status:
  loadBalancer: {}
